clone_folder: C:\projects\appveyor
image: Visual Studio 2017
platform: x64
configuration: Release
before_build: 
- cmd: >-
    dir C:\Libraries

    mkdir build

    cd build

    set generator="Visual Studio 15 2017 Win64"

    cmake .. -G %generator%
build_script: 
- cmd: >-
    cmake --build . --config %configuration%
