cache:
  - C:\Tools\vcpkg\installed\
  - C:\Tools\ninja\ninja.exe

configuration: Release

environment:
  VCPKG_DIR: C:\Tools\vcpkg
  NINJA_DIR: C:\Tools\ninja
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      PLATFORM: x86
      GENERATOR: 'Ninja'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      PLATFORM: x64
      GENERATOR: 'Ninja'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
      ARCHITECTURE: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      PLATFORM: x86
      GENERATOR: 'Ninja'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      ARCHITECTURE: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      PLATFORM: x64
      GENERATOR: 'Ninja'
      VCVARSALL: '%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
      ARCHITECTURE: amd64

init:
  - cd %VCPKG_DIR%
  - git pull
  - echo.set(VCPKG_BUILD_TYPE release)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
  - .\bootstrap-vcpkg.bat
  - vcpkg version
  - cd %APPVEYOR_BUILD_FOLDER%

install:
  - vcpkg install boost eigen3 flann qhull gtest --triplet %PLATFORM%-windows
  - set PATH=%VCPKG_DIR%\installed\%PLATFORM%-windows\bin;%PATH%
  - if not exist %NINJA_DIR%\ mkdir %NINJA_DIR%
  - cd %NINJA_DIR%
  - if not exist ninja.exe appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  - if not exist ninja.exe 7z x ninja-win.zip
  - set PATH=%NINJA_DIR%;%PATH%

build:
  parallel: true

build_script:
  - call "%VCVARSALL%" %ARCHITECTURE%
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G"%GENERATOR%"
          -DCMAKE_C_COMPILER=cl.exe
          -DCMAKE_CXX_COMPILER=cl.exe
          -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake
          -DVCPKG_APPLOCAL_DEPS=OFF
          -DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=ON
          -DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=ON
          -DPCL_NO_PRECOMPILE=OFF
          -DBUILD_simulation=ON
          -DBUILD_global_tests=OFF
          -DBUILD_examples=OFF
          -DBUILD_tools=OFF
          -DBUILD_apps=OFF
          ..
  - cmake --build . --config %CONFIGURATION%
  #- ctest -C %CONFIGURATION% -V