cache:
  - C:\Tools\vcpkg\installed\
  - C:\Tools\ninja\

configuration: Release

environment:
  VCPKG_DIR: C:\Tools\vcpkg
  NINJA_DIR: C:\Tools\ninja
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x86
      GENERATOR: "Ninja"
      VSDEVCMD: "%PROGRAMFILES(X86)%\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
      ARCHITECTURE: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PLATFORM: x64
      GENERATOR: "Ninja"
      VSDEVCMD: "%PROGRAMFILES(X86)%\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
      ARCHITECTURE: amd64
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x86
      GENERATOR: "Ninja"
      VSDEVCMD: "%PROGRAMFILES(X86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
      ARCHITECTURE: x86
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      PLATFORM: x64
      GENERATOR: "Ninja"
      VSDEVCMD: "%PROGRAMFILES(X86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
      ARCHITECTURE: amd64

init:
  - cd %VCPKG_DIR%
  - git pull
  - echo.set(VCPKG_BUILD_TYPE release)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
  - .\bootstrap-vcpkg.bat
  - vcpkg version
  - set PATH=%VCPKG_DIR%\installed\%PLATFORM%-windows\bin;%PATH%
  - mkdir %NINJA_DIR% > NUL 2>&1
  - cd %NINJA_DIR%
  - if not exist ninja-win.zip appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  - if not exist ninja.exe 7z x ninja-win.zip
  - set PATH=%NINJA_DIR%;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%

install:
  - vcpkg install boost eigen3 flann qhull gtest --triplet %PLATFORM%-windows

build:
  parallel: true

build_script:
  - call "%VSDEVCMD%" -host_arch=x86 -arch=%ARCHITECTURE%
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G"%GENERATOR%"
          -DCMAKE_C_COMPILER=cl.exe
          -DCMAKE_CXX_COMPILER=cl.exe
          -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake
          -DVCPKG_APPLOCAL_DEPS=OFF
          -DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=ON
          -DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=ON
          -DPCL_NO_PRECOMPILE=OFF
          -DBUILD_simulation=ON
          -DBUILD_global_tests=ON
          -DBUILD_examples=OFF
          -DBUILD_tools=OFF
          -DBUILD_apps=OFF
          ..
  - cmake --build . --config %CONFIGURATION%
  #- ctest -C %CONFIGURATION% -V