image:
  - Visual Studio 2015
  - Visual Studio 2017

cache:
  - c:\tools\vcpkg\installed\

install:
  - cd c:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg version
  - vcpkg install boost:x64-windows eigen3:x64-windows flann:x64-windows qhull:x64-windows

platform: x64

configuration: Release

build:
  parallel: true

build_script:
  - cd c:\projects\appveyor
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . --config Release