clone_folder: C:\projects\appveyor

image:
  #- Visual Studio 2015
  - Visual Studio 2017

platform:
  #- Win32
  - x64

configuration:
  #- Debug
  - Release

before_build:
  - cmd: >-
    mkdir build
    cd build
    set generator="Visual Studio 15 2017 Win64"
    'cmake .. -G %generator%'

build_script:
  - cmd: >-
    'cmake --build . --config %configuration%'
